# DO NOT EDIT THIS FILE!
#
# Python module Fortune__POA generated by omniidl

import omniORB
omniORB.updateModule("Fortune__POA")

# ** 1. Stub files contributing to this module
import fortune_idl

# ** 2. Sub-modules

# ** 3. End
