
// Interface for the messaging cordination


module Messaging {
	struct Clock {
		long id;
		long ts;
	};
	typedef sequence<Clock> VectorClock;

	interface Receiver {
		void send(in long id, in VectorClock ts, in long value);
		long get_id();
	};

	typedef sequence<Receiver> ReceiverSeq;

	interface Coordinator {
		long register(in Receiver rec);
		void unregister(in long id);
		boolean ready();
		ReceiverSeq receivers();
	};
};

