# DO NOT EDIT THIS FILE!
#
# Python module Messaging generated by omniidl

import omniORB
omniORB.updateModule("Messaging")

# ** 1. Stub files contributing to this module
import message_cordinator_idl

# ** 2. Sub-modules

# ** 3. End
