# DO NOT EDIT THIS FILE!
#
# Python module Messaging__POA generated by omniidl

import omniORB
omniORB.updateModule("Messaging__POA")

# ** 1. Stub files contributing to this module
import message_cordinator_idl

# ** 2. Sub-modules

# ** 3. End
